### ISSUE TITLE
Create a tag for the original code

### ISSUE THREAD

**Issue by meekee7** [OpenTrespasser/JurassicParkTrespasser#27]
Commit `#a0a6292` on the `master` branch is the last commit before actual code revisions (sort of) begin. It would be very neat if we could have a _tag_ that state here on GitHub. (A Git tag is like an immutable branch.) The original code would be directly preserved in case someone wants to study it.

Perhaps that tag could be advertised in the root `README.MD`.

**Comment by GamerDude27** [comment]
Preserving the code has always been an idea besides this project. Recent code commits were actually meant for the `dev` branch but got pushed to `master` because I did it in a tired state.

~~I'll be creating a new branch called `original` (for preservation only) without any of the new commits.~~

**Update:**
You can now find the original source code here:
https://github.com/OpenTrespasser/JurassicParkTrespasser/releases/tag/original
